name: Secrets Scan with Trivy

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  scan:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.actor, '[bot]') }} # [bot]を含む場合は除外する
    steps:
    - name: Checkout
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with:
        ref: ${{ github.head_ref }}

    - name: Run Aqua Security Trivy
      uses: aquasecurity/trivy-action@915b19bbe73b92a6cf82a1bc12b087c9a19a5fe2 # 0.28.0
      with:
        scan-type: fs
        scan-ref: . # default
        severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL # default
        scanners: secret
        output: trivy.txt
        exit-code: 1

    - name: Post PR comments
      if: failure()
      env:
        GITHUB_TOKEN: ${{ github.token }}
        URL: ${{ github.event.pull_request.html_url }}
      run: |
        sed -i -e '1i ```' -e '$a ```\nこのactionについては [Notion](https://www.notion.so/globisorg/GitHub-dcb884f8df2646df8d8e686bd6290d46) を参照。' trivy.txt
        gh pr comment -F ./trivy.txt "${URL}" 
